[package]
name = "permission"
version = "0.8.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
protocol = { path = "../protocol" }
telemetry = { path = "../telemetry" }
traits = { path = "../traits" }
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["io-util", "io-std"] }
tracing.workspace = true
regex = "1"

[dev-dependencies]
tools = { path = "../tools" }
tokio = { workspace = true, features = ["io-util", "rt-multi-thread", "macros"] }

[lints]
workspace = true
