[package]
name = "providers"
version = "0.11.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
protocol = { path = "../protocol" }
traits = { path = "../traits" }
api-client = { path = "../api-client" }
cost = { path = "../cost" }
serde_json.workspace = true
thiserror.workspace = true
async-trait.workspace = true
futures = { workspace = true }
gcp_auth = "0.12"
tokio = { workspace = true, features = ["sync"] }
aws-sigv4 = "1"
aws-credential-types = "1"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "sync"] }

[lints]
workspace = true
