#!/usr/bin/env bash
#
# Build and stage the pinned OpenMinis iSH ARM64 runtime artifacts used by the
# native iOS mobile-linux bridge.
#
# This script intentionally stages generated artifacts under `clients/ios/build/`
# only. Nothing under the stage directory should be committed.
#
# Inputs (pinned in-repo):
#   - docs/superpowers/references/OpenMinis/deps/build_ish.sh
#   - docs/superpowers/references/OpenMinis/deps/prepare_alpine_rootfs.sh
#
# Outputs:
#   clients/ios/build/linux-runtime/openminis/
#     include/
#     libs/
#     resources/{libvdso.so.elf,alpine-rootfs,alpine-rootfs.zip,default_mount}
#     xcode/openminis-ish.xcconfig
#     manifest.json
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IOS_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${IOS_DIR}/../.." && pwd)"
OPENMINIS_ROOT="${REPO_ROOT}/docs/superpowers/references/OpenMinis"
DEPS_DIR="${OPENMINIS_ROOT}/deps"

BUILD_ISH="${DEPS_DIR}/build_ish.sh"
PREPARE_ROOTFS="${DEPS_DIR}/prepare_alpine_rootfs.sh"

STAGE_ROOT="${IOS_DIR}/build/linux-runtime/openminis"
STAGE_INCLUDE="${STAGE_ROOT}/include"
STAGE_LIBS="${STAGE_ROOT}/libs"
STAGE_RESOURCES="${STAGE_ROOT}/resources"
STAGE_XCODE="${STAGE_ROOT}/xcode"

BUILD_TYPE="release"
ALPINE_VERSION="3.21"
CLEAN=0

usage() {
  cat <<'EOF'
Usage: clients/ios/scripts/build-linux-runtime.sh [options]

Options:
  --clean                 Remove the staged output before rebuilding
  --debug                 Use OpenMinis debug iSH build artifacts
  --release               Use OpenMinis release iSH build artifacts (default)
  --alpine-version <ver>  Pass a version to prepare_alpine_rootfs.sh (default: 3.21)
  -h, --help              Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --clean)
      CLEAN=1
      shift
      ;;
    --debug)
      BUILD_TYPE="debug"
      shift
      ;;
    --release)
      BUILD_TYPE="release"
      shift
      ;;
    --alpine-version)
      ALPINE_VERSION="${2:?missing value for --alpine-version}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

for required in "$BUILD_ISH" "$PREPARE_ROOTFS"; do
  [[ -x "$required" || -f "$required" ]] || {
    echo "Missing pinned OpenMinis helper: $required" >&2
    exit 1
  }
done

if [[ "$CLEAN" == "1" ]]; then
  rm -rf "${STAGE_ROOT}"
fi

mkdir -p "${STAGE_INCLUDE}" "${STAGE_LIBS}" "${STAGE_RESOURCES}" "${STAGE_XCODE}"

echo "[build-linux-runtime] Building pinned OpenMinis iSH (${BUILD_TYPE})"
bash "${BUILD_ISH}" "${BUILD_TYPE}"

echo "[build-linux-runtime] Preparing pinned Alpine rootfs (${ALPINE_VERSION})"
bash "${PREPARE_ROOTFS}" "${ALPINE_VERSION}"

echo "[build-linux-runtime] Staging headers, static libs, and resources"
rsync -a --delete "${DEPS_DIR}/include/" "${STAGE_INCLUDE}/"
rsync -a --delete "${DEPS_DIR}/libs/" "${STAGE_LIBS}/"

mkdir -p "${STAGE_RESOURCES}/default_mount"
if [[ -f "${DEPS_DIR}/resources/libvdso.so.elf" ]]; then
  cp "${DEPS_DIR}/resources/libvdso.so.elf" "${STAGE_RESOURCES}/libvdso.so.elf"
fi
if [[ -d "${DEPS_DIR}/resources/alpine-rootfs" ]]; then
  rsync -a --delete "${DEPS_DIR}/resources/alpine-rootfs/" "${STAGE_RESOURCES}/alpine-rootfs/"
  rm -f "${STAGE_RESOURCES}/alpine-rootfs.zip"
  (
    cd "${STAGE_RESOURCES}"
    ditto -c -k --sequesterRsrc --keepParent "alpine-rootfs" "alpine-rootfs.zip"
  )
fi
if [[ -d "${OPENMINIS_ROOT}/src/ios/default_mount" ]]; then
  rsync -a --delete "${OPENMINIS_ROOT}/src/ios/default_mount/" "${STAGE_RESOURCES}/default_mount/"
fi

MANIFEST="${STAGE_ROOT}/manifest.json"
ROOTFS_SHA=""
if [[ -f "${STAGE_RESOURCES}/alpine-rootfs.zip" ]]; then
  ROOTFS_SHA="$(shasum -a 256 "${STAGE_RESOURCES}/alpine-rootfs.zip" | awk '{print $1}')"
fi

cat > "${STAGE_XCODE}/openminis-ish.xcconfig" <<EOF
// Generated by clients/ios/scripts/build-linux-runtime.sh
HEADER_SEARCH_PATHS = \$(inherited) ${STAGE_INCLUDE}
LIBRARY_SEARCH_PATHS = \$(inherited) ${STAGE_LIBS}
OTHER_CFLAGS = \$(inherited) -DLINGXI_ENABLE_OPENMINIS_ISH=1
OTHER_LDFLAGS = \$(inherited) ${STAGE_LIBS}/libish.a ${STAGE_LIBS}/libish_emu.a ${STAGE_LIBS}/libfakefs.a
EOF

cat > "${MANIFEST}" <<EOF
{
  "generated_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "source_root": "${OPENMINIS_ROOT}",
  "build_type": "${BUILD_TYPE}",
  "alpine_version": "${ALPINE_VERSION}",
  "stage_root": "${STAGE_ROOT}",
  "rootfs_zip_sha256": "${ROOTFS_SHA}",
  "link_xcconfig": "${STAGE_XCODE}/openminis-ish.xcconfig",
  "resources": {
    "rootfs_zip": "${STAGE_RESOURCES}/alpine-rootfs.zip",
    "rootfs_dir": "${STAGE_RESOURCES}/alpine-rootfs",
    "default_mount": "${STAGE_RESOURCES}/default_mount",
    "vdso": "${STAGE_RESOURCES}/libvdso.so.elf"
  }
}
EOF

echo "[build-linux-runtime] Stage complete"
echo "  root:      ${STAGE_ROOT}"
echo "  xcconfig:  ${STAGE_XCODE}/openminis-ish.xcconfig"
echo "  manifest:  ${MANIFEST}"
if [[ -n "${ROOTFS_SHA}" ]]; then
  echo "  rootfs sha256: ${ROOTFS_SHA}"
fi
