// swift-tools-version:5.9
// M8-P12 skeleton — the LingxiCode Swift package.
//
// `LingxiCodeBindings` is the UniFFI-generated target (produced in M9 by
// `uniffi-bindgen generate … --language swift` from the `ios-framework`
// staticlib). `LingxiCode` is the hand-written ergonomic wrapper + the native
// callback-interface implementations (camera / voice / share).
import PackageDescription

let package = Package(
    name: "LingxiCode",
    platforms: [.iOS(.v16)],
    products: [
        .library(name: "LingxiCode", targets: ["LingxiCode"])
    ],
    targets: [
        // Generated by UniFFI in M9 (Sources/LingxiCodeBindings/*.swift +
        // the lingxi_code_bindings_FFI module map over the staticlib).
        .target(name: "LingxiCodeBindings"),
        .target(name: "LingxiCode", dependencies: ["LingxiCodeBindings"]),
    ]
)
