import "./globals.css";

export const metadata = {
  title: "LingXi Local App",
  description: "A local-first app generated by LingXi",
};

/**
 * `viewportFit: "cover"` is load-bearing, not cosmetic: the native bootstraps
 * measure the device safe area by reading `env(safe-area-inset-*)` off a probe
 * element, and under the default `viewport-fit=auto` every one of those
 * resolves to 0. Without it `deviceContext.safeArea` is always {0,0,0,0} and
 * generated bottom navigation clips under the iPhone home indicator.
 */
export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-CN">
      <body>{children}</body>
    </html>
  );
}
