import "./globals.css";

export const metadata = {
  title: "LingXi Local App",
  description: "A local-first app generated by LingXi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-CN">
      <body>{children}</body>
    </html>
  );
}
