package com.lingxi.code.settings

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import com.lingxi.code.R

@Composable
internal fun settingsLabel(text: String): String = when (text) {
    "Model region" -> stringResource(R.string.settings_provider_region)
    "International" -> stringResource(R.string.settings_provider_region_international)
    "China mainland" -> stringResource(R.string.settings_provider_region_china)
    "Defaults to international. Apply saved settings when idle to change the running region." -> stringResource(R.string.settings_provider_region_help)
    "Personal" -> stringResource(R.string.settings_parity_personal)
    "Models & services" -> stringResource(R.string.settings_parity_models_services)
    "Coding" -> stringResource(R.string.settings_parity_coding)
    "General" -> stringResource(R.string.settings_parity_general)
    "Voice" -> stringResource(R.string.settings_parity_voice)
    "Archived chats" -> stringResource(R.string.settings_parity_archived)
    "Projects & trust" -> stringResource(R.string.settings_parity_projects_trust)
    "Provider credentials" -> stringResource(R.string.settings_parity_credentials)
    "Custom providers & routing" -> stringResource(R.string.settings_parity_custom_providers)
    "Fusion" -> stringResource(R.string.settings_parity_fusion)
    "Permissions" -> stringResource(R.string.settings_parity_permissions)
    "Tools & agent behavior" -> stringResource(R.string.settings_parity_tools_agent)
    "Hooks" -> stringResource(R.string.settings_parity_hooks)
    "Plugins & marketplace" -> stringResource(R.string.settings_parity_plugins)
    "Diagnostics" -> stringResource(R.string.settings_parity_diagnostics)
    "Search settings" -> stringResource(R.string.settings_parity_search)
    "Inherit" -> stringResource(R.string.settings_parity_inherit)
    "Managed policy: read-only" -> stringResource(R.string.settings_parity_managed_readonly)
    "Waiting for engine settings snapshot…" -> stringResource(R.string.settings_parity_wait_snapshot)
    "Connect an engine to view and edit its configuration. Device settings remain available." -> stringResource(R.string.settings_parity_disconnected)
    "Discard draft and reload" -> stringResource(R.string.settings_parity_discard_draft)
    "This layer changed while you were editing. Review your draft before saving." -> stringResource(R.string.settings_parity_external_change)
    "Choose model" -> stringResource(R.string.settings_parity_choose_model)
    "Search models" -> stringResource(R.string.settings_parity_search_models)
    "Enable Fusion" -> stringResource(R.string.settings_parity_enable_fusion)
    "Add panel model" -> stringResource(R.string.settings_parity_add_panel)
    "Analyst" -> stringResource(R.string.settings_parity_analyst)
    "Synthesizer" -> stringResource(R.string.settings_parity_synthesizer)
    "Edits replace only the chosen key in this layer. Effective values can include other layers. Use null to inherit." -> stringResource(R.string.settings_parity_layer_explanation)
    "Layer data unavailable" -> stringResource(R.string.settings_parity_layer_unavailable)
    "All three roles are required. Choose 2–8 distinct panel models." -> stringResource(R.string.settings_parity_fusion_roles_required)
    "No matching models. Refresh the engine model catalog or configure a provider." -> stringResource(R.string.settings_parity_no_models)
    "Refresh from engine" -> stringResource(R.string.settings_parity_refresh_engine)
    "Configuration files" -> stringResource(R.string.settings_parity_configuration_files)
    "Skill documents" -> stringResource(R.string.settings_parity_skill_documents)
    "Refresh catalog" -> stringResource(R.string.settings_parity_refresh_catalog)
    "Create skill" -> stringResource(R.string.settings_parity_create_skill)
    "Skill name" -> stringResource(R.string.settings_parity_skill_name)
    "Save skill" -> stringResource(R.string.settings_parity_save_skill)
    "Move skill to trash" -> stringResource(R.string.settings_parity_skill_trash)
    "New server" -> stringResource(R.string.settings_parity_new_server)
    "Server name" -> stringResource(R.string.settings_parity_server_name)
    "Save server" -> stringResource(R.string.settings_parity_save_server)
    "Remove server" -> stringResource(R.string.settings_parity_remove_server)
    "Refresh servers" -> stringResource(R.string.settings_parity_refresh_servers)
    "Validate hooks" -> stringResource(R.string.settings_parity_validate_hooks)
    "Save hooks" -> stringResource(R.string.settings_parity_save_hooks)
    "Effective hooks" -> stringResource(R.string.settings_parity_effective_hooks)
    "Marketplace source" -> stringResource(R.string.settings_parity_marketplace_source)
    "Preview adding marketplace" -> stringResource(R.string.settings_parity_preview_marketplace)
    "Confirm and apply" -> stringResource(R.string.settings_parity_confirm_apply)
    "New profile ID" -> stringResource(R.string.settings_parity_new_profile)
    "Add profile" -> stringResource(R.string.settings_parity_add_profile)
    "Base URL" -> stringResource(R.string.settings_parity_base_url)
    "API key environment variable" -> stringResource(R.string.settings_parity_api_key_env)
    "Add model" -> stringResource(R.string.settings_parity_add_model)
    "Remove profile from this layer" -> stringResource(R.string.settings_parity_remove_profile)
    "Alias" -> stringResource(R.string.settings_parity_alias)
    "Add alias" -> stringResource(R.string.settings_parity_add_alias)
    "Device & mobile capabilities" -> stringResource(R.string.settings_parity_mobile_capabilities)
    "Provider accounts" -> stringResource(R.string.settings_parity_provider_accounts)
    "Manage provider credentials" -> stringResource(R.string.settings_parity_manage_credentials)
    "User" -> stringResource(R.string.settings_parity_user_layer)
    "Project" -> stringResource(R.string.settings_parity_project_layer)
    "Local" -> stringResource(R.string.settings_parity_local_layer)
    "Managed" -> stringResource(R.string.settings_parity_managed_layer)
    "Account" -> stringResource(R.string.settings_title_account)
    "Appearance" -> stringResource(R.string.settings_appearance)
    "Skills" -> stringResource(R.string.settings_title_skills)
    "MCP servers" -> stringResource(R.string.settings_mcp_servers)
    "About" -> stringResource(R.string.settings_section_about)
    "Advanced" -> stringResource(R.string.settings_section_advanced)
    "Save" -> stringResource(R.string.settings_save)
    "Cancel" -> stringResource(R.string.common_cancel)
    "Remove" -> stringResource(R.string.settings_parity_remove)
    "Language" -> stringResource(R.string.settings_language_title)
    "Notifications" -> stringResource(R.string.settings_notifications)
    "Voice & audio" -> stringResource(R.string.settings_voice_audio)
    "Permission mode" -> stringResource(R.string.settings_permission_mode_title)
    "TypeScript language server" -> stringResource(R.string.settings_typescript_lsp_title)
    "Linux runtime" -> stringResource(R.string.settings_linux_runtime)
    "Scheduled tasks" -> stringResource(R.string.settings_title_cron)
    "Replay onboarding" -> stringResource(R.string.settings_rewatch_onboarding)
    "Open-source licenses" -> stringResource(R.string.settings_title_open_source)
    "user" -> stringResource(R.string.settings_parity_user_layer)
    "project" -> stringResource(R.string.settings_parity_project_layer)
    "local" -> stringResource(R.string.settings_parity_local_layer)
    "managed" -> stringResource(R.string.settings_parity_managed_layer)
    // 每一层「值落到哪、影响谁」的一句话。四个裸标签本身不解释任何东西，而它们的
    // 差别有真实后果：项目层的文件随仓库提交给整个团队，本地层的被 gitignore。
    "user_layer_desc" -> stringResource(R.string.settings_parity_user_layer_desc)
    "project_layer_desc" -> stringResource(R.string.settings_parity_project_layer_desc)
    "local_layer_desc" -> stringResource(R.string.settings_parity_local_layer_desc)
    "managed_layer_desc" -> stringResource(R.string.settings_parity_managed_layer_desc)
    "Current project" -> stringResource(R.string.settings_parity_current_project)
    "Switch project" -> stringResource(R.string.settings_parity_switch_project)
    "Switching the project also switches your current conversation." -> stringResource(R.string.settings_parity_switch_project_warning)
    "Checking with the engine which project this layer writes to…" -> stringResource(R.string.settings_parity_project_unknown)
    // MCP 的作用域与设置层同名不同义，「本地」的含义正好相反 —— 见 ConfigurationManagers.kt。
    "mcp_scope_user_desc" -> stringResource(R.string.mcp_scope_user_desc)
    "mcp_scope_local_desc" -> stringResource(R.string.mcp_scope_local_desc)
    "mcp_scope_project_desc" -> stringResource(R.string.mcp_scope_project_desc)
    "mcp_scope_vs_layers_note" -> stringResource(R.string.mcp_scope_vs_layers_note)
    "Not configured" -> stringResource(R.string.settings_parity_not_configured)
    "Choose" -> stringResource(R.string.settings_parity_choose)
    "Panel models" -> stringResource(R.string.settings_parity_panel_models)
    "No configured model advertises Fusion analyst support. Refresh the engine catalog after configuring a supported provider." -> stringResource(R.string.settings_parity_no_analyst)
    "Restore" -> stringResource(R.string.settings_parity_restore)
    "Archive" -> stringResource(R.string.settings_parity_archive)
    "No archived conversations" -> stringResource(R.string.settings_parity_empty_archive)
    "Archive a conversation" -> stringResource(R.string.settings_parity_archive_conversation)
    "Effective value" -> stringResource(R.string.settings_parity_effective_value)
    "Default" -> stringResource(R.string.settings_parity_default)
    "Merged across layers" -> stringResource(R.string.settings_parity_merged_layers)
    "Output style" -> stringResource(R.string.settings_parity_output_style)
    "Default permission mode" -> stringResource(R.string.settings_parity_default_permission)
    "Keyboard & input" -> stringResource(R.string.settings_keyboard_input)
    "Data & privacy" -> stringResource(R.string.settings_data_privacy)
    "Plugin secret" -> stringResource(R.string.settings_parity_plugin_secret)
    "Configured" -> stringResource(R.string.settings_parity_secret_configured)
    "Unknown" -> stringResource(R.string.settings_parity_secret_unknown)
    "Saved securely. Reconnect the engine to apply the plugin secret." -> stringResource(R.string.settings_parity_secret_saved_reconnect)
    "Deleted securely. Reconnect the engine to clear the cached plugin secret." -> stringResource(R.string.settings_parity_secret_deleted_reconnect)
    "Secure storage operation failed. Please retry." -> stringResource(R.string.settings_parity_secret_failed)
    "Reconnect engine" -> stringResource(R.string.settings_parity_reconnect)
    "Refresh status" -> stringResource(R.string.settings_parity_refresh_status)
    "Import providers" -> stringResource(R.string.settings_parity_import_providers)
    "Paste LingXi providers JSON or OpenCode provider JSON. Review the selected profiles before importing." -> stringResource(R.string.settings_parity_import_intro)
    "Provider import JSON" -> stringResource(R.string.settings_parity_import_json)
    "Choose JSON file" -> stringResource(R.string.settings_parity_import_choose_file)
    "Preview import" -> stringResource(R.string.settings_parity_import_preview)
    "Import selected providers" -> stringResource(R.string.settings_parity_import_apply)
    "Edit sanitized JSON" -> stringResource(R.string.settings_parity_import_edit_sanitized)
    "Replaces an existing profile when selected." -> stringResource(R.string.settings_parity_import_conflict)
    "API key detected; it will be stored separately in secure credential storage." -> stringResource(R.string.settings_parity_import_secret_detected)
    "Invalid JSON. Check quotes, commas and braces." -> stringResource(R.string.settings_parity_import_invalid)
    "Invalid provider shape. Check the definition in the source JSON." -> stringResource(R.string.settings_parity_import_invalid_provider)
    "Unsupported configuration. Remove unsupported request fields before importing." -> stringResource(R.string.settings_parity_import_unsupported)
    "Provider import exceeds 2 MB" -> stringResource(R.string.settings_parity_import_too_large)
    "Could not read the JSON file. Select a UTF-8 JSON file under 2 MB." -> stringResource(R.string.settings_parity_import_file_failed)
    "Engine source changed; preview the import again" -> stringResource(R.string.settings_parity_import_source_changed)
    "This layer changed since preview. Review the import again before saving." -> stringResource(R.string.settings_parity_import_layer_changed)
    "The engine did not confirm the provider import. Review is retained; refresh settings before retrying." -> stringResource(R.string.settings_parity_import_not_confirmed)
    "Provide an API key, an apiKeyEnv name, or an existing stored credential for every selected provider." -> stringResource(R.string.settings_parity_import_credentials_required)
    "An imported credential could not be stored. Provider settings were not written; previously stored credentials are retained." -> stringResource(R.string.settings_parity_import_credential_failed)
    "Only provider definitions are imported. Other top-level settings are ignored." -> stringResource(R.string.settings_parity_import_top_ignored)
    "OpenCode model metadata is not converted; review model capabilities." -> stringResource(R.string.settings_parity_import_models_warning)
    "OpenCode labels and model filters are not imported." -> stringResource(R.string.settings_parity_import_filters_warning)
    "Select at least one provider" -> stringResource(R.string.settings_parity_import_select_required)
    "Invalid provider configuration. Check the profile ID and optional fields." -> stringResource(R.string.settings_parity_provider_validation_invalid)
    "Store secrets in provider credentials, not provider configuration" -> stringResource(R.string.settings_parity_provider_validation_secret)
    "Models require distinct, nonempty IDs." -> stringResource(R.string.settings_parity_provider_validation_models)
    "Use an HTTP(S) base URL without embedded credentials" -> stringResource(R.string.settings_parity_provider_validation_url)
    "Use an environment variable name for apiKeyEnv" -> stringResource(R.string.settings_parity_provider_validation_env)
    "Choose a supported provider protocol" -> stringResource(R.string.settings_parity_provider_validation_protocol)
    "Pricing must reference configured models and use finite, nonnegative values." -> stringResource(R.string.settings_parity_provider_validation_pricing)
    "Edit import JSON" -> stringResource(R.string.settings_parity_import_edit_source)
    "Apply saved settings" -> stringResource(R.string.settings_parity_apply_saved)
    "Saved settings will apply after reconnecting the engine." -> stringResource(R.string.settings_parity_saved_pending)
    "Save or discard your drafts before reconnecting." -> stringResource(R.string.settings_parity_draft_reconnect_blocked)
    else -> when {
        text.startsWith("Invalid profile ID:") -> stringResource(R.string.settings_parity_provider_validation_invalid)
        text.contains("requires at least one model") || text.contains("requires nonempty distinct model") -> stringResource(R.string.settings_parity_provider_validation_models)
        text.startsWith("Unsupported") || text.startsWith("Use provider or providers") || text.startsWith("No provider definitions") -> stringResource(R.string.settings_parity_import_unsupported)
        text.startsWith("Pricing") -> stringResource(R.string.settings_parity_provider_validation_pricing)
        else -> text
    }
}
