//! Extension → language display-name mapping for the
//! `claude_code.code_edit_tool.decision` counter's `language` attribute.
//!
//! 1:1 port of the binary's `UMt(path)` resolver (2.1.220): `path.extname`
//! minus the dot, lowercased, resolved through the highlight.js registry —
//! canonical ids (`aur`), aliases (`lur`, e.g. `rs → rust`, `ts →
//! typescript`), then the static extras (`ACs`: `cedar`/`cedarpolicy`) —
//! falling back to `"unknown"`. The dynamic plugin-language branch (`Btd`,
//! fed by highlight plugins registered at runtime) has no LingXi equivalent
//! and is an empty set at CC boot, so it is omitted.
//!
//! The table below is GENERATED from the 2.1.220 binary (`aur` ∪ resolved
//! `lur` ∪ `ACs`, 385 arms) — regenerate with the extraction script rather
//! than hand-editing entries.

/// Resolve the `language` attribute for a code-edit tool decision from the
/// tool's target file path (binary `UMt`). Returns `"unknown"` for missing,
/// empty, or unmapped extensions — the attribute is still attached in that
/// case, exactly like CC (only a missing PATH omits it; see the caller).
#[must_use]
pub(crate) fn language_for_path(path: &str) -> &'static str {
    let Some(ext) = file_extension(path) else {
        return "unknown";
    };
    if ext.is_empty() {
        return "unknown";
    }
    language_for_extension(&ext.to_lowercase())
}

/// Node `path.extname(path).slice(1)`: the substring after the last `.` of the
/// basename. `None` when there is no `.`, or the `.` is the basename's first
/// character (dotfiles like `.bashrc` have no extension); `Some("")` for a
/// trailing dot (`foo.`), which the caller maps to `"unknown"`.
fn file_extension(path: &str) -> Option<&str> {
    let base = path.rsplit('/').next().unwrap_or(path);
    let dot = base.rfind('.')?;
    if dot == 0 {
        return None;
    }
    Some(&base[dot + 1..])
}

/// The merged `aur`/`lur`/`ACs` lookup, keyed by lowercased extension.
#[allow(clippy::too_many_lines, reason = "generated 1:1 table from the binary")]
fn language_for_extension(ext: &str) -> &'static str {
    match ext {
        "1c" => "1C:Enterprise",
        "abnf" => "Augmented Backus-Naur Form",
        "accesslog" => "Apache Access Log",
        "actionscript" => "ActionScript",
        "ada" => "Ada",
        "ado" => "Stata",
        "adoc" => "AsciiDoc",
        "ahk" => "AutoHotkey",
        "angelscript" => "AngelScript",
        "apache" => "Apache config",
        "apacheconf" => "Apache config",
        "applescript" => "AppleScript",
        "arcade" => "ArcGIS Arcade",
        "arduino" => "Arduino",
        "arm" => "ARM Assembly",
        "armasm" => "ARM Assembly",
        "as" => "ActionScript",
        "asc" => "AngelScript",
        "asciidoc" => "AsciiDoc",
        "aspectj" => "AspectJ",
        "atom" => "HTML, XML",
        "autohotkey" => "AutoHotkey",
        "autoit" => "AutoIt",
        "avrasm" => "AVR Assembly",
        "awk" => "Awk",
        "axapta" => "X++",
        "bash" => "Bash",
        "basic" => "BASIC",
        "bat" => "Batch file (DOS)",
        "bf" => "Brainfuck",
        "bind" => "DNS Zone",
        "bnf" => "Backus–Naur Form",
        "brainfuck" => "Brainfuck",
        "c" => "C",
        "c#" => "C#",
        "c++" => "C++",
        "cal" => "C/AL",
        "capnp" => "Cap’n Proto",
        "capnproto" => "Cap’n Proto",
        "cc" => "C++",
        "cedar" => "Cedar",
        "cedarpolicy" => "Cedar",
        "ceylon" => "Ceylon",
        "cjs" => "JavaScript",
        "clean" => "Clean",
        "clj" => "Clojure",
        "clojure" => "Clojure",
        "clojure-repl" => "Clojure REPL",
        "cls" => "Caché Object Script",
        "cmake" => "CMake",
        "cmake.in" => "CMake",
        "cmd" => "Batch file (DOS)",
        "coffee" => "CoffeeScript",
        "coffeescript" => "CoffeeScript",
        "console" => "Shell Session",
        "coq" => "Coq",
        "cos" => "Caché Object Script",
        "cpp" => "C++",
        "cr" => "Crystal",
        "craftcms" => "Twig",
        "crm" => "crmsh",
        "crmsh" => "crmsh",
        "crystal" => "Crystal",
        "cs" => "C#",
        "csharp" => "C#",
        "cson" => "CoffeeScript",
        "csp" => "CSP",
        "css" => "CSS",
        "cts" => "TypeScript",
        "cxx" => "C++",
        "d" => "D",
        "dart" => "Dart",
        "dcl" => "Clean",
        "delphi" => "Delphi",
        "dfm" => "Delphi",
        "diff" => "Diff",
        "django" => "Django",
        "dns" => "DNS Zone",
        "do" => "Stata",
        "docker" => "Dockerfile",
        "dockerfile" => "Dockerfile",
        "dos" => "Batch file (DOS)",
        "dpr" => "Delphi",
        "dsconfig" => "dsconfig",
        "dst" => "Dust",
        "dts" => "Device Tree",
        "dust" => "Dust",
        "ebnf" => "Extended Backus-Naur Form",
        "edn" => "Clojure",
        "elixir" => "Elixir",
        "elm" => "Elm",
        "erb" => "ERB",
        "erl" => "Erlang",
        "erlang" => "Erlang",
        "erlang-repl" => "Erlang REPL",
        "ex" => "Elixir",
        "excel" => "Excel formulae",
        "exs" => "Elixir",
        "f#" => "F#",
        "f90" => "Fortran",
        "f95" => "Fortran",
        "feature" => "Gherkin",
        "fix" => "FIX",
        "flix" => "Flix",
        "fortran" => "Fortran",
        "freepascal" => "Delphi",
        "fs" => "F#",
        "fsharp" => "F#",
        "gams" => "GAMS",
        "gauss" => "GAUSS",
        "gcode" => "G-code (ISO 6983)",
        "gemspec" => "Ruby",
        "gherkin" => "Gherkin",
        "glsl" => "GLSL",
        "gml" => "GML",
        "gms" => "GAMS",
        "go" => "Go",
        "golang" => "Go",
        "golo" => "Golo",
        "gql" => "GraphQL",
        "gradle" => "Gradle",
        "graph" => "Roboconf",
        "graphql" => "GraphQL",
        "groovy" => "Groovy",
        "gss" => "GAUSS",
        "gyp" => "Python",
        "h" => "C",
        "h++" => "C++",
        "haml" => "HAML",
        "handlebars" => "Handlebars",
        "haskell" => "Haskell",
        "haxe" => "Haxe",
        "hbs" => "Handlebars",
        "hh" => "C++",
        "hpp" => "C++",
        "hs" => "Haskell",
        "hsp" => "HSP",
        "html" => "HTML, XML",
        "html.handlebars" => "Handlebars",
        "html.hbs" => "Handlebars",
        "htmlbars" => "Handlebars",
        "http" => "HTTP",
        "https" => "HTTP",
        "hx" => "Haxe",
        "hxx" => "C++",
        "hy" => "Hy",
        "hylang" => "Hy",
        "i7" => "Inform 7",
        "iced" => "CoffeeScript",
        "icl" => "Clean",
        "inform7" => "Inform 7",
        "ini" => "TOML, also INI",
        "ino" => "Arduino",
        "instances" => "Roboconf",
        "ipython" => "Python",
        "irb" => "Ruby",
        "irpf90" => "IRPF90",
        "isbl" => "ISBL",
        "java" => "Java",
        "javascript" => "JavaScript",
        "jboss-cli" => "JBoss CLI",
        "jinja" => "Django",
        "jldoctest" => "Julia REPL",
        "js" => "JavaScript",
        "json" => "JSON",
        "jsonc" => "JSON",
        "jsp" => "Java",
        "jsx" => "JavaScript",
        "julia" => "Julia",
        "julia-repl" => "Julia REPL",
        "k" => "Q",
        "kdb" => "Q",
        "kotlin" => "Kotlin",
        "kt" => "Kotlin",
        "kts" => "Kotlin",
        "lasso" => "Lasso",
        "lassoscript" => "Lasso",
        "latex" => "LaTeX",
        "lazarus" => "Delphi",
        "ldif" => "LDIF",
        "leaf" => "Leaf",
        "less" => "Less",
        "lfm" => "Delphi",
        "lisp" => "Lisp",
        "livecodeserver" => "LiveCode",
        "livescript" => "LiveScript",
        "llvm" => "LLVM IR",
        "lpr" => "Delphi",
        "ls" => "LiveScript",
        "lsl" => "LSL (Linden Scripting Language)",
        "lua" => "Lua",
        "m" => "Mercury",
        "mak" => "Makefile",
        "make" => "Makefile",
        "makefile" => "Makefile",
        "markdown" => "Markdown",
        "mathematica" => "Mathematica",
        "matlab" => "Matlab",
        "maxima" => "Maxima",
        "md" => "Markdown",
        "mel" => "MEL",
        "mercury" => "Mercury",
        "mikrotik" => "MikroTik RouterOS script",
        "mips" => "MIPS Assembly",
        "mipsasm" => "MIPS Assembly",
        "mizar" => "Mizar",
        "mjs" => "JavaScript",
        "mk" => "Makefile",
        "mkd" => "Markdown",
        "mkdown" => "Markdown",
        "ml" => "SML (Standard ML)",
        "mm" => "Objective-C",
        "mma" => "Mathematica",
        "mojolicious" => "Mojolicious",
        "monkey" => "Monkey",
        "moo" => "Mercury",
        "moon" => "MoonScript",
        "moonscript" => "MoonScript",
        "mts" => "TypeScript",
        "mysql" => "SQL",
        "n1ql" => "N1QL",
        "nc" => "G-code (ISO 6983)",
        "nestedtext" => "Nested Text",
        "nginx" => "Nginx config",
        "nginxconf" => "Nginx config",
        "nim" => "Nim",
        "nix" => "Nix",
        "nixos" => "Nix",
        "node-repl" => "Node REPL",
        "nsis" => "NSIS",
        "nt" => "Nested Text",
        "obj-c" => "Objective-C",
        "obj-c++" => "Objective-C",
        "objc" => "Objective-C",
        "objective-c++" => "Objective-C",
        "objectivec" => "Objective-C",
        "ocaml" => "OCaml",
        "openscad" => "OpenSCAD",
        "oracle" => "SQL",
        "osascript" => "AppleScript",
        "oxygene" => "Oxygene",
        "p21" => "STEP Part 21",
        "parser3" => "Parser3",
        "pas" => "Delphi",
        "pascal" => "Delphi",
        "patch" => "Diff",
        "pb" => "PureBASIC",
        "pbi" => "PureBASIC",
        "pcmk" => "crmsh",
        "pde" => "Processing",
        "perl" => "Perl",
        "pf" => "Packet Filter config",
        "pf.conf" => "Packet Filter config",
        "pgsql" => "PostgreSQL",
        "php" => "php",
        "php-template" => "PHP template",
        "php3" => "php",
        "php4" => "php",
        "php5" => "php",
        "php6" => "php",
        "php7" => "php",
        "php8" => "php",
        "pl" => "Perl",
        "plaintext" => "Plain text",
        "plist" => "HTML, XML",
        "pluto" => "Lua",
        "pm" => "Perl",
        "podspec" => "Ruby",
        "pony" => "Pony",
        "postgres" => "PostgreSQL",
        "postgresql" => "PostgreSQL",
        "powershell" => "PowerShell",
        "pp" => "Puppet",
        "processing" => "Processing",
        "profile" => "Python profiler",
        "prolog" => "Prolog",
        "properties" => ".properties",
        "proto" => "Protocol Buffers",
        "protobuf" => "Protocol Buffers",
        "ps" => "PowerShell",
        "ps1" => "PowerShell",
        "puppet" => "Puppet",
        "purebasic" => "PureBASIC",
        "pwsh" => "PowerShell",
        "py" => "Python",
        "pycon" => "python-repl",
        "python" => "Python",
        "python-repl" => "python-repl",
        "q" => "Q",
        "qml" => "QML",
        "qt" => "QML",
        "r" => "R",
        "rb" => "Ruby",
        "re" => "ReasonML",
        "reasonml" => "ReasonML",
        "rib" => "RenderMan RIB",
        "roboconf" => "Roboconf",
        "routeros" => "MikroTik RouterOS script",
        "rs" => "Rust",
        "rsl" => "RenderMan RSL",
        "rss" => "HTML, XML",
        "ruby" => "Ruby",
        "ruleslanguage" => "Oracle Rules Language",
        "rust" => "Rust",
        "sas" => "SAS",
        "scad" => "OpenSCAD",
        "scala" => "Scala",
        "scheme" => "Scheme",
        "sci" => "Scilab",
        "scilab" => "Scilab",
        "scm" => "Scheme",
        "scss" => "SCSS",
        "sh" => "Bash",
        "shell" => "Shell Session",
        "shellsession" => "Shell Session",
        "smali" => "Smali",
        "smalltalk" => "Smalltalk",
        "sml" => "SML (Standard ML)",
        "sqf" => "SQF",
        "sql" => "SQL",
        "st" => "Smalltalk",
        "stan" => "Stan",
        "stanfuncs" => "Stan",
        "stata" => "Stata",
        "step" => "STEP Part 21",
        "step21" => "STEP Part 21",
        "stp" => "STEP Part 21",
        "styl" => "Stylus",
        "stylus" => "Stylus",
        "subunit" => "SubUnit",
        "sv" => "Verilog",
        "svg" => "HTML, XML",
        "svh" => "Verilog",
        "swift" => "Swift",
        "taggerscript" => "Tagger Script",
        "tao" => "XL",
        "tap" => "Test Anything Protocol",
        "tcl" => "Tcl",
        "tex" => "LaTeX",
        "text" => "Plain text",
        "thor" => "Ruby",
        "thrift" => "Thrift",
        "tk" => "Tcl",
        "toml" => "TOML, also INI",
        "tp" => "TP",
        "ts" => "TypeScript",
        "tsx" => "TypeScript",
        "twig" => "Twig",
        "txt" => "Plain text",
        "typescript" => "TypeScript",
        "v" => "Verilog",
        "vala" => "Vala",
        "vb" => "Visual Basic .NET",
        "vbnet" => "Visual Basic .NET",
        "vbs" => "VBScript",
        "vbscript" => "VBScript",
        "vbscript-html" => "VBScript in HTML",
        "verilog" => "Verilog",
        "vhdl" => "VHDL",
        "vim" => "Vim Script",
        "wasm" => "WebAssembly",
        "wildfly-cli" => "JBoss CLI",
        "wl" => "Mathematica",
        "wren" => "Wren",
        "wsf" => "HTML, XML",
        "x++" => "X++",
        "x86asm" => "Intel x86 Assembly",
        "xhtml" => "HTML, XML",
        "xjb" => "HTML, XML",
        "xl" => "XL",
        "xls" => "Excel formulae",
        "xlsx" => "Excel formulae",
        "xml" => "HTML, XML",
        "xpath" => "XQuery",
        "xq" => "XQuery",
        "xqm" => "XQuery",
        "xquery" => "XQuery",
        "xsd" => "HTML, XML",
        "xsl" => "HTML, XML",
        "yaml" => "YAML",
        "yml" => "YAML",
        "zep" => "Zephir",
        "zephir" => "Zephir",
        "zone" => "DNS Zone",
        "zsh" => "Bash",
        _ => "unknown",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn common_extensions_resolve_via_aliases() {
        // lur alias → aur display name.
        assert_eq!(language_for_path("/tmp/main.rs"), "Rust");
        assert_eq!(language_for_path("a/b/app.ts"), "TypeScript");
        assert_eq!(language_for_path("x.py"), "Python");
        assert_eq!(language_for_path("mod.tsx"), "TypeScript");
        assert_eq!(language_for_path("h.cpp"), "C++");
    }

    #[test]
    fn canonical_ids_resolve_directly() {
        assert_eq!(language_for_path("q.rust"), "Rust");
        assert_eq!(language_for_path("conf.toml"), "TOML, also INI");
        assert_eq!(language_for_path("s.cedar"), "Cedar");
    }

    #[test]
    fn case_is_folded_like_to_lower_case() {
        assert_eq!(language_for_path("MAIN.RS"), "Rust");
    }

    #[test]
    fn unknown_missing_and_dotfile_extensions() {
        assert_eq!(language_for_path("Makefile.custom-ext"), "unknown");
        assert_eq!(language_for_path("noext"), "unknown");
        assert_eq!(language_for_path("/etc/.bashrc"), "unknown");
        assert_eq!(language_for_path("trailing."), "unknown");
        // .ipynb is absent from the highlight.js registry in the binary too.
        assert_eq!(language_for_path("nb.ipynb"), "unknown");
    }
}
